arch: arm64

dist: xenial
language: go

go:
- 1.11.x

services:
- docker

cache:
  directories:
    - $HOME/packer

addons:
  apt:
    update: true
    packages:
    - kpartx

before_script:
- "echo commit: $TRAVIS_COMMIT"
- "echo tag: $TRAVIS_TAG"
- "echo branch: $TRAVIS_BRANCH"
- "echo build: $TRAVIS_BUILD_NUMBER"
- bash bin/travis-packer.sh

jobs:
  include:
    - stage: docker
      name: "pimba/librespot docker image build & publication"
      script:
      - cd librespot && make build
      - docker images
      - |
        if [ "$TRAVIS_BRANCH" = master ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push docker.io/pimba/librespot
        fi
    -
      name: "pimba/shairport docker image build & publication"
      script:
      - cd shairport && make build
      - docker images
      - |
        if [ "$TRAVIS_BRANCH" = master ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push docker.io/pimba/shairport
        fi
    -
      name: "pimba/mopidy docker image build & publication"
      script:
      - cd mopidy && make build
      - docker images
      - |
        if [ "$TRAVIS_BRANCH" = master ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push docker.io/pimba/mopidy
        fi
    - stage: packer
      name: "enlarge raspbian disk image and activate ssh"
      script:
      - wget -nv https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip
      - sudo ~/packer/bin/packer build packer.json
      - ls -lh pimba.img
