dist: xenial
language: minimal

before_install:
- sudo docker run --privileged linuxkit/binfmt:v0.6
- sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/armhf
- sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
- export BUILDKIT_HOST=tcp://0.0.0.0:1234

services:
- docker

jobs:
  include:
    - stage: build
      name: "pimba/librespot docker image build"
      script:
      - |
        buildctl build --frontend=dockerfile.v0 \
            --opt platform=linux/armhf \
            --opt filename=./Dockerfile \
            --local dockerfile=./librespot \
            --local context=./librespot \
            --output type=docker,name=docker.io/pimba/librespot | docker load
      - docker images
    -
      name: "pimba/shairport docker image build"
      script:
      - |
        buildctl build --frontend=dockerfile.v0 \
            --opt platform=linux/armhf \
            --opt filename=./Dockerfile \
            --local dockerfile=./shairport \
            --local context=./shairport \
            --output type=docker,name=docker.io/pimba/shairport | docker load
      - docker images
    -
      name: "pimba/mopidy docker image build"
      script:
      - |
        buildctl build --frontend=dockerfile.v0 \
            --opt platform=linux/armhf \
            --opt filename=./Dockerfile \
            --local dockerfile=./mopidy \
            --local context=./mopidy \
            --output type=docker,name=docker.io/pimba/mopidy | docker load
      - docker images
