dist: xenial
language: go

go:
- 1.13.x

services:
- docker

cache:
  directories:
    - $HOME/qemu
    - $HOME/packer

addons:
  apt:
    update: true
    packages:
    - kpartx
    - python-pip

before_install:
- sudo docker run --privileged linuxkit/binfmt:v0.6

before_script:
- "echo commit: $TRAVIS_COMMIT"
- "echo tag: $TRAVIS_TAG"
- "echo branch: $TRAVIS_BRANCH"
- "echo build: $TRAVIS_BUILD_NUMBER"
- bash bin/travis-qemu.sh
- bash bin/travis-packer.sh
- sudo pip install ansible

jobs:
  include:
    - stage: lint
      name: "running shellchecker"
      script:
      -  make lint
    - stage: test
      name: "running tests"
      script:
      -  make test
    - stage: packer
      name: "build pimba disk image"
      script:
      - sudo ln -s $HOME/qemu/bin/qemu-arm /usr/local/bin/qemu-arm-static
      - wget -nv https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip
      - |
        while sleep 9m; do
          echo "====[ $SECONDS seconds still running ]===="
        done &
        make zip
      - ls -lh pimba.img
      - sha256sum pimba.img*
