- name: get docker repository gpg key
  apt_key: url=https://download.docker.com/linux/debian/gpg

- name: add docker package list
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: deb [arch=armhf] https://download.docker.com/linux/debian {{ debian_distro }} stable

- name: install packages
  apt: pkg={{ packages_to_install }} state=present update_cache=yes
