- name: get docker repository gpg key
  apt_key: url=https://download.docker.com/linux/debian/gpg

- name: add docker package list
  apt_repository:
    filename: docker
    repo: deb [arch=armhf] https://download.docker.com/linux/debian {{ debian_distro }} stable

- name: install packages
  apt:
    state: present
    update_cache: yes
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
