- name: Download ini2env and unpack it
  unarchive:
    src: https://github.com/endemics/ini2env/releases/download/v0.1.1/ini2env_0.1.1_linux_arm64.tgz
    remote_src: yes
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
