- name: Create pimba config folder
  file:
    path: /boot/pimba/
    recurse: yes
    state: directory

- name: copy docker-compose file
  copy:
    src: files/boot/docker-compose.yaml
    dest: /boot/pimba/docker-compose.yaml

- name: systemd service for docker-compose
  copy:
    src: files/etc/pimba.service
    dest: /etc/systemd/system/pimba.service

- name: enable and start pimba systemd service
  systemd: name=pimba.service enabled=yes state=started daemon_reload=yes
