- name: allow glibc to cache timezone
  copy:
    src: files/etc/environment
    dest: /etc/environment

- name: Set root password to 'musicbox'
  user:
    name: root
    password: musicbox

- name: Make sure disk resize is not automatically set for first boot
  file:
    path: /etc/init.d/resize2fs_once
    state: absent
