---
name: build

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint
        run: make test

  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   id: qemu
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     image: tonistiigi/binfmt:latest
      #     platforms: arm

      - name: Validate Template
        uses: endemics/packer-github-actions@c0173ddff61ac8263a4e105af3709e6f4293e5e6
        with:
          command: validate
          target: packer.json

      - name: Download Raspbian iso 
        run: wget -nv https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip

      - name: Build Artifact
        uses: endemics/packer-github-actions@c0173ddff61ac8263a4e105af3709e6f4293e5e6
        with:
          command: build
          target: packer.json
